# Assignment 18: Text Vectorization Techniques

Dataset Name: TMDB 5000 Movie Dataset

Kaggle Link: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

In [157]:
import pandas as pd

In [158]:
df = pd.read_csv('./IMDB_cleaned.csv')

In [159]:
data = df.copy()

In [160]:
data.head()

,review,final_clean_text
0,one of the other reviewers has mentioned that ...,one reviewer mention watch oz episode youll ho...
1,a wonderful little production br br the filmin...,wonderful little production film technique una...
2,i thought this was a wonderful way to spend ti...,think wonderful way spend time hot summer week...
3,basically theres a family where a little boy j...,basically there family little boy jake think t...
4,petter matteis love in the time of money is a ...,petter matteis love time money visually stunni...

In [161]:
data.shape

(50000, 2)

## Task 1: Manula One-Hot Encoding

In [162]:
sentences = df["final_clean_text"].dropna().head(10).tolist()

for sentence in sentences:
    print(sentence)

one reviewer mention watch oz episode youll hook right exactly happen methe first thing strike oz brutality unflinching scene violence set right word go trust show faint hearted timid show pull punch regard drug sex violence hardcore classic use wordit call oz nickname give oswald maximum security state penitentary focus mainly emerald city experimental section prison cell glass front face inwards privacy high agenda em city home manyaryans muslims gangsta latino christian italian irish moreso scuffle death stare dodgy dealing shady agreement never far awayi would say main appeal show due fact go show wouldnt dare forget pretty picture paint mainstream audience forget charm forget romanceoz doesnt mess around first episode ever saw struck nasty surreal couldnt say ready watch developed taste oz get accustomed high level graphic violence violence injustice crook guard wholl sell nickel inmates wholl kill order get away well mannered middle class inmate turn prison bitch due lack street skill prison experience watch oz may become comfortable uncomfortable viewingthats get touch darker side
wonderful little production film technique unassuming oldtimebbc fashion give comfort sometimes discomforting sense realism entire piece actor extremely well choose michael sheen get polari voice pat truly see seamless edit guided reference williams diary entry well worth watch terrificly write perform piece masterful production one great master comedy life realism really come home little thing fantasy guard rather use traditional dream technique remain solid disappears play knowledge sens particularly scene concern orton halliwell set particularly flat halliwells mural decorate every surface terribly well do
think wonderful way spend time hot summer weekend sit air condition theater watch lighthearted comedy plot simplistic dialogue witty character likable even well bread suspect serial killer may disappoint realize match point risk addiction think proof woody allen still fully control style many u grow lovethis id laugh one woodys comedy year dare say decade ive never impressed scarlet johanson manage tone sexy image jump right average spirit young womanthis may crown jewel career witty devil wear prada interest superman great comedy go see friend
basically there family little boy jake think theres zombie closet parent fight timethis movie slow soap opera suddenly jake decides become rambo kill zombieok first youre go make film must decide thriller drama drama movie watchable parent divorce argue like real life jake closet totally ruin film expect see boogeyman similar movie instead watch drama meaningless thriller spot well play parent descent dialog shot jake ignore
petter matteis love time money visually stunning film watch mr mattei offer u vivid portrait human relation movie seem tell u money power success people different situation encounter variation arthur schnitzlers play theme director transfer action present time new york different character meet connect one connect one way another next person one seem know previous point contact stylishly film sophisticate luxurious look take see people live world live habitatthe thing one get souls picture different stage loneliness one inhabit big city exactly best place human relation find sincere fulfillment one discern case people encounterthe act good mr matteis direction steve buscemi rosario dawson carol kane michael imperioli adrian grenier rest talented cast make character come alivewe wish mr mattei good luck await anxiously next work
probably alltime favorite movie story selflessness sacrifice dedication noble cause preachy bore never get old despite see time last year paul lukas performance bring tear eye bette davis one truly sympathetic role delight kid grandma say like dressedup midget child make fun watch mother slow awaken whats happen world roof believable startle dozen thumb theyd movie
sure would like see resurrection date seahunt series tech today would bring back kid excitement mei grow black white tv seahunt gunsmoke heros every weekyou vote comeback new sea huntwe need change pace tv would work world water adventureoh way thank outlet like view many viewpoint tv many moviesso ole way believe ive get wan na saywould nice read plus point sea huntif rhyme would line would let submitor leave doubt quitif must go let
show amazing fresh innovative idea first air first year brilliant thing drop show really funny anymore continued decline complete waste time todayits truly disgraceful far show fall write painfully bad performance almost bad mildly entertaining respite guesthosts show probably wouldnt still air find hard believe creator handselected original cast also choose band hack follow one recognize brilliance see fit replace mediocrity felt must give star respect original cast make show huge success show awful cant believe still air
encourage positive comment film look forward watch film bad mistake ive see film truly one bad awful almost every way edit pace storyline act soundtrack film song lame country tune play less four time film look cheap nasty boring extreme rarely happy see end credit film thing prevents give score harvey keitel far best performance least seem make bite effort one keitel obsessive
like original gut wrench laughter like movie young old love movie hell even mom liked itgreat camp

In [163]:
# Create vocabulary
vocabulary = set()
for sentence in sentences:
    words = sentence.split()
    for word in words:
        vocabulary.add(word)
vocabulary = sorted(list(vocabulary))

print(vocabulary)

['accustomed', 'act', 'action', 'actor', 'addiction', 'adrian', 'adventureoh', 'agenda', 'agreement', 'air', 'alivewe', 'allen', 'alltime', 'almost', 'also', 'amazing', 'another', 'anxiously', 'anymore', 'appeal', 'argue', 'around', 'arthur', 'audience', 'average', 'await', 'awaken', 'away', 'awayi', 'awful', 'back', 'bad', 'band', 'basically', 'become', 'believable', 'believe', 'best', 'bette', 'big', 'bitch', 'bite', 'black', 'boogeyman', 'bore', 'boring', 'boy', 'bread', 'brilliance', 'brilliant', 'bring', 'brutality', 'buscemi', 'call', 'camp', 'cant', 'career', 'carol', 'case', 'cast', 'cause', 'cell', 'change', 'character', 'charm', 'cheap', 'child', 'choose', 'christian', 'city', 'class', 'classic', 'closet', 'come', 'comeback', 'comedy', 'comfort', 'comfortable', 'comment', 'complete', 'concern', 'condition', 'connect', 'contact', 'continued', 'control', 'couldnt', 'country', 'creator', 'credit', 'crook', 'crown', 'dare', 'darker', 'date', 'davis', 'dawson', 'dealing', 'death', 'decade', 'decide', 'decides', 'decline', 'decorate', 'dedication', 'delight', 'descent', 'despite', 'developed', 'devil', 'dialog', 'dialogue', 'diary', 'different', 'direction', 'director', 'disappears', 'disappoint', 'discern', 'discomforting', 'disgraceful', 'divorce', 'do', 'dodgy', 'doesnt', 'doubt', 'dozen', 'drama', 'dream', 'dressedup', 'drop', 'drug', 'due', 'edit', 'effort', 'em', 'emerald', 'encounter', 'encounterthe', 'encourage', 'end', 'entertaining', 'entire', 'entry', 'episode', 'even', 'ever', 'every', 'exactly', 'excitement', 'expect', 'experience', 'experimental', 'extreme', 'extremely', 'eye', 'face', 'fact', 'faint', 'fall', 'family', 'fantasy', 'far', 'fashion', 'favorite', 'felt', 'fight', 'film', 'find', 'first', 'fit', 'flat', 'focus', 'follow', 'forget', 'forward', 'four', 'fresh', 'friend', 'front', 'fulfillment', 'fully', 'fun', 'funny', 'gangsta', 'get', 'give', 'glass', 'go', 'good', 'grandma', 'graphic', 'great', 'grenier', 'grow', 'guard', 'guesthosts', 'guided', 'gunsmoke', 'gut', 'habitatthe', 'hack', 'halliwell', 'halliwells', 'handselected', 'happen', 'happy', 'hard', 'hardcore', 'harvey', 'hearted', 'hell', 'heros', 'high', 'home', 'hook', 'hot', 'huge', 'human', 'huntif', 'huntwe', 'id', 'idea', 'ignore', 'image', 'imperioli', 'impressed', 'inhabit', 'injustice', 'inmate', 'inmates', 'innovative', 'instead', 'interest', 'inwards', 'irish', 'italian', 'itgreat', 'ive', 'jake', 'jewel', 'johanson', 'jump', 'kane', 'keitel', 'kid', 'kill', 'killer', 'know', 'knowledge', 'lack', 'lame', 'last', 'latino', 'laugh', 'laughter', 'least', 'leave', 'less', 'let', 'level', 'life', 'lighthearted', 'likable', 'like', 'liked', 'line', 'little', 'live', 'loneliness', 'look', 'love', 'lovethis', 'luck', 'lukas', 'luxurious', 'main', 'mainly', 'mainstream', 'make', 'manage', 'mannered', 'many', 'manyaryans', 'master', 'masterful', 'match', 'mattei', 'matteis', 'maximum', 'may', 'meaningless', 'mediocrity', 'meet', 'mei', 'mention', 'mess', 'methe', 'michael', 'middle', 'midget', 'mildly', 'mistake', 'mom', 'money', 'moreso', 'mother', 'movie', 'moviesso', 'mr', 'mural', 'muslims', 'must', 'na', 'nasty', 'need', 'never', 'new', 'next', 'nice', 'nickel', 'nickname', 'noble', 'obsessive', 'offer', 'old', 'oldtimebbc', 'ole', 'one', 'opera', 'order', 'original', 'orton', 'oswald', 'outlet', 'oz', 'pace', 'painfully', 'paint', 'parent', 'particularly', 'pat', 'paul', 'penitentary', 'people', 'perform', 'performance', 'person', 'petter', 'picture', 'piece', 'place', 'play', 'plot', 'plus', 'point', 'polari', 'portrait', 'positive', 'power', 'prada', 'preachy', 'present', 'pretty', 'prevents', 'previous', 'prison', 'privacy', 'probably', 'production', 'proof', 'pull', 'punch', 'quitif', 'rambo', 'rarely', 'rather', 'read', 'ready', 'real', 'realism', 'realize', 'really', 'recognize', 'reference', 'regard', 'relation', 'remain', 'replace', 'respect', 'respite', 'rest', 'resurrection', 'reviewer', 'rhyme', 'right', 'risk', 'role', 'romanceoz', 'roof', 'rosario', 'ruin', 'sacrifice', 'saw', 'say', 'saywould', 'scarlet', 'scene', 'schnitzlers', 'score', 'scuffle', 'sea', 'seahunt', 'seamless', 'section', 'security', 'see', 'seem', 'selflessness', 'sell', 'sens', 'sense', 'serial', 'series', 'set', 'sex', 'sexy', 'shady', 'sheen', 'shot', 'show', 'side', 'similar', 'simplistic', 'sincere', 'sit', 'situation', 'skill', 'slow', 'soap', 'solid', 'sometimes', 'song', 'sophisticate', 'souls', 'soundtrack', 'spend', 'spirit', 'spot', 'stage', 'star', 'stare', 'startle', 'state', 'steve', 'still', 'story', 'storyline', 'street', 'strike', 'struck', 'stunning', 'style', 'stylishly', 'submitor', 'success', 'suddenly', 'summer', 'superman', 'sure', 'surface', 'surreal', 'suspect', 'sympathetic', 'take', 'talented', 'taste', 'tear', 'tech', 'technique', 'tell', 'terribly', 'terrificly', 'thank', 'theater', 'theme', 'there', 'theres', 'theyd', 'thing', 'think', 'thriller', 'thumb', 'time', 'timethis', 'timid', 'today', 'todayits', 'tone', 'totally', 'touch', 'traditional', 'transfer', 'truly', 'trust', 'tune', 'turn', 'tv', 'u', 'unassuming', 'uncomfortable', 'unflinching', 'use', 'variation', 'view', 'viewingthats', 'viewpoint', 'violence', 'visually', 'vivid', 'voice', 'vote', 'wan', 'waste', 'watch', 'watchable', 'water', 'way', 'wear', 'weekend', 'weekyou', 'well', 'whats', 'white', 'wholl', 'williams', 'wish', 'witty', 'womanthis', 'wonderful', 'woody', 'woodys', 'word', 'wordit', 'work', 'world', 'worth', 'would', 'wouldnt', 'wrench', 'write', 'year', 'york', 'youll', 'young', 'youre', 'zombie', 'zombieok']

In [164]:
one_hot_vectors = []

for sentence in sentences:
    words = sentence.split()
    vector = []
    for word in vocabulary:
        if word in words:
            vector.append(1)
        else:
            vector.append(0)
    
    one_hot_vectors.append(vector)

In [165]:
for i in range(len(sentences)):
    print('vectos', one_hot_vectors[i])

vectos [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0]
vectos [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
vectos [0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0]
vectos [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1]
vectos [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
vectos [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
vectos [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
vectos [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0]
vectos [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
vectos [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0]

In [166]:
one_hot_matrix = pd.DataFrame(
    one_hot_vectors,
    columns=vocabulary
)

print(one_hot_matrix)

   accustomed  act  action  actor  addiction  adrian  adventureoh  agenda  \
0           1    0       0      0          0       0            0       1
1           0    0       0      1          0       0            0       0
2           0    0       0      0          1       0            0       0
3           0    0       0      0          0       0            0       0
4           0    1       1      0          0       1            0       0
5           0    0       0      0          0       0            0       0
6           0    0       0      0          0       0            1       0
7           0    0       0      0          0       0            0       0
8           0    1       0      0          0       0            0       0
9           0    0       0      0          0       0            0       0

   agreement  air  ...  wouldnt  wrench  write  year  york  youll  young  \
0          1    0  ...        1       0      0     0     0      1      0
1          0    0  ...        0       0      1     0     0      0      0
2          0    1  ...        0       0      0     1     0      0      1
3          0    0  ...        0       0      0     0     0      0      0
4          0    0  ...        0       0      0     0     1      0      0
5          0    0  ...        0       0      0     1     0      0      0
6          0    0  ...        0       0      0     0     0      0      0
7          0    1  ...        1       0      1     1     0      0      0
8          0    0  ...        0       0      0     0     0      0      0
9          0    0  ...        0       1      0     0     0      0      1

   youre  zombie  zombieok
0      0       0         0
1      0       0         0
2      0       0         0
3      1       1         1
4      0       0         0
5      0       0         0
6      0       0         0
7      0       0         0
8      0       0         0
9      0       0         0

[10 rows x 558 columns]

## Task 2: One Hot Encoding using Scikit Learn

In [167]:
from sklearn.feature_extraction.text import CountVectorizer

In [168]:
vectorizer = CountVectorizer(binary=True)

In [169]:
encoded_matrix = vectorizer.fit_transform(sentences)

Vocabulary

In [170]:
len(vectorizer.get_feature_names_out())

557

In [171]:
print(vectorizer.get_feature_names_out())

['accustomed' 'act' 'action' 'actor' 'addiction' 'adrian' 'adventureoh'
 'agenda' 'agreement' 'air' 'alivewe' 'allen' 'alltime' 'almost' 'also'
 'amazing' 'another' 'anxiously' 'anymore' 'appeal' 'argue' 'around'
 'arthur' 'audience' 'average' 'await' 'awaken' 'away' 'awayi' 'awful'
 'back' 'bad' 'band' 'basically' 'become' 'believable' 'believe' 'best'
 'bette' 'big' 'bitch' 'bite' 'black' 'boogeyman' 'bore' 'boring' 'boy'
 'bread' 'brilliance' 'brilliant' 'bring' 'brutality' 'buscemi' 'call'
 'camp' 'cant' 'career' 'carol' 'case' 'cast' 'cause' 'cell' 'change'
 'character' 'charm' 'cheap' 'child' 'choose' 'christian' 'city' 'class'
 'classic' 'closet' 'come' 'comeback' 'comedy' 'comfort' 'comfortable'
 'comment' 'complete' 'concern' 'condition' 'connect' 'contact'
 'continued' 'control' 'couldnt' 'country' 'creator' 'credit' 'crook'
 'crown' 'dare' 'darker' 'date' 'davis' 'dawson' 'dealing' 'death'
 'decade' 'decide' 'decides' 'decline' 'decorate' 'dedication' 'delight'
 'descent' 'despite' 'developed' 'devil' 'dialog' 'dialogue' 'diary'
 'different' 'direction' 'director' 'disappears' 'disappoint' 'discern'
 'discomforting' 'disgraceful' 'divorce' 'do' 'dodgy' 'doesnt' 'doubt'
 'dozen' 'drama' 'dream' 'dressedup' 'drop' 'drug' 'due' 'edit' 'effort'
 'em' 'emerald' 'encounter' 'encounterthe' 'encourage' 'end'
 'entertaining' 'entire' 'entry' 'episode' 'even' 'ever' 'every' 'exactly'
 'excitement' 'expect' 'experience' 'experimental' 'extreme' 'extremely'
 'eye' 'face' 'fact' 'faint' 'fall' 'family' 'fantasy' 'far' 'fashion'
 'favorite' 'felt' 'fight' 'film' 'find' 'first' 'fit' 'flat' 'focus'
 'follow' 'forget' 'forward' 'four' 'fresh' 'friend' 'front' 'fulfillment'
 'fully' 'fun' 'funny' 'gangsta' 'get' 'give' 'glass' 'go' 'good'
 'grandma' 'graphic' 'great' 'grenier' 'grow' 'guard' 'guesthosts'
 'guided' 'gunsmoke' 'gut' 'habitatthe' 'hack' 'halliwell' 'halliwells'
 'handselected' 'happen' 'happy' 'hard' 'hardcore' 'harvey' 'hearted'
 'hell' 'heros' 'high' 'home' 'hook' 'hot' 'huge' 'human' 'huntif'
 'huntwe' 'id' 'idea' 'ignore' 'image' 'imperioli' 'impressed' 'inhabit'
 'injustice' 'inmate' 'inmates' 'innovative' 'instead' 'interest'
 'inwards' 'irish' 'italian' 'itgreat' 'ive' 'jake' 'jewel' 'johanson'
 'jump' 'kane' 'keitel' 'kid' 'kill' 'killer' 'know' 'knowledge' 'lack'
 'lame' 'last' 'latino' 'laugh' 'laughter' 'least' 'leave' 'less' 'let'
 'level' 'life' 'lighthearted' 'likable' 'like' 'liked' 'line' 'little'
 'live' 'loneliness' 'look' 'love' 'lovethis' 'luck' 'lukas' 'luxurious'
 'main' 'mainly' 'mainstream' 'make' 'manage' 'mannered' 'many'
 'manyaryans' 'master' 'masterful' 'match' 'mattei' 'matteis' 'maximum'
 'may' 'meaningless' 'mediocrity' 'meet' 'mei' 'mention' 'mess' 'methe'
 'michael' 'middle' 'midget' 'mildly' 'mistake' 'mom' 'money' 'moreso'
 'mother' 'movie' 'moviesso' 'mr' 'mural' 'muslims' 'must' 'na' 'nasty'
 'need' 'never' 'new' 'next' 'nice' 'nickel' 'nickname' 'noble'
 'obsessive' 'offer' 'old' 'oldtimebbc' 'ole' 'one' 'opera' 'order'
 'original' 'orton' 'oswald' 'outlet' 'oz' 'pace' 'painfully' 'paint'
 'parent' 'particularly' 'pat' 'paul' 'penitentary' 'people' 'perform'
 'performance' 'person' 'petter' 'picture' 'piece' 'place' 'play' 'plot'
 'plus' 'point' 'polari' 'portrait' 'positive' 'power' 'prada' 'preachy'
 'present' 'pretty' 'prevents' 'previous' 'prison' 'privacy' 'probably'
 'production' 'proof' 'pull' 'punch' 'quitif' 'rambo' 'rarely' 'rather'
 'read' 'ready' 'real' 'realism' 'realize' 'really' 'recognize'
 'reference' 'regard' 'relation' 'remain' 'replace' 'respect' 'respite'
 'rest' 'resurrection' 'reviewer' 'rhyme' 'right' 'risk' 'role'
 'romanceoz' 'roof' 'rosario' 'ruin' 'sacrifice' 'saw' 'say' 'saywould'
 'scarlet' 'scene' 'schnitzlers' 'score' 'scuffle' 'sea' 'seahunt'
 'seamless' 'section' 'security' 'see' 'seem' 'selflessness' 'sell' 'sens'
 'sense' 'serial' 'series' 'set' 'sex' 'sexy' 'shady' 'sheen' 'shot'
 'show' 'side' 'similar' 'simplistic' 'sincere' 'sit' 'situation' 'skill'
 'slow' 'soap' 'solid' 'sometimes' 'song' 'sophisticate' 'souls'
 'soundtrack' 'spend' 'spirit' 'spot' 'stage' 'star' 'stare' 'startle'
 'state' 'steve' 'still' 'story' 'storyline' 'street' 'strike' 'struck'
 'stunning' 'style' 'stylishly' 'submitor' 'success' 'suddenly' 'summer'
 'superman' 'sure' 'surface' 'surreal' 'suspect' 'sympathetic' 'take'
 'talented' 'taste' 'tear' 'tech' 'technique' 'tell' 'terribly'
 'terrificly' 'thank' 'theater' 'theme' 'there' 'theres' 'theyd' 'thing'
 'think' 'thriller' 'thumb' 'time' 'timethis' 'timid' 'today' 'todayits'
 'tone' 'totally' 'touch' 'traditional' 'transfer' 'truly' 'trust' 'tune'
 'turn' 'tv' 'unassuming' 'uncomfortable' 'unflinching' 'use' 'variation'
 'view' 'viewingthats' 'viewpoint' 'violence' 'visually' 'vivid' 'voice'
 'vote' 'wan' 'waste' 'watch' 'watchable' 'water' 'way' 'wear' 'weekend'
 'weekyou' 'well' 'whats' 'white' 'wholl' 'williams' 'wish' 'witty'
 'womanthis' 'wonderful' 'woody' 'woodys' 'word' 'wordit' 'work' 'world'
 'worth' 'would' 'wouldnt' 'wrench' 'write' 'year' 'york' 'youll' 'young'
 'youre' 'zombie' 'zombieok']

### Encoded matrix

In [172]:
print(encoded_matrix.toarray())

[[1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

# Part 2: Bag of Words(BoW)

## Task 3: Bag of Words Representation

In [173]:
from sklearn.feature_extraction.text import CountVectorizer

In [187]:
texts = df["final_clean_text"].fillna("")

In [188]:
bow = CountVectorizer()
bow_matrix = bow.fit_transform(texts)

In [189]:
vocabulary = bow.get_feature_names_out()

len(vocabulary)

203208

In [190]:
len(bow.vocabulary_)

203208

In [191]:
bow_matrix[:5].toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [192]:
bow_df = pd.DataFrame(
    bow_matrix[:5,:10].toarray(),
    columns=vocabulary[:10]
)

In [193]:
# Bow Dataframe 
bow_df

,aa,aaa,aaaaaaaaaaaahhhhhhhhhhhhhh,aaaaaaaargh,aaaaaaah,aaaaaaahhhhhhggg,aaaaagh,aaaaah,aaaaargh,aaaaarrrrrrgggggghhhhhh
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0

## Task 3: Calculate total Frequence

In [194]:
word_frequency = bow_matrix.sum(axis=0)
word_frequency = word_frequency.A1

In [195]:
frequency_df = pd.DataFrame({"word": vocabulary,"frequency": word_frequency})
frequency_df.head()

                         word  frequency
0                          aa         20
1                         aaa         15
2  aaaaaaaaaaaahhhhhhhhhhhhhh          1
3                 aaaaaaaargh          1
4                    aaaaaaah          1

Note: Bag of Words represents each document using word counts. If a word appears multiple times in a document, its value will be higher. By adding the columns of the BoW matrix, we can calculate the total frequency of each word in the complete dataset. Therefore, BoW provides information about how often each word occurs.

# Part 3

In [202]:
unigram_vectorizer = CountVectorizer(
    ngram_range=(1, 1)
)

In [203]:
unigram_matrix = unigram_vectorizer.fit_transform(texts)

In [205]:
unigram_vocabulary = unigram_vectorizer.get_feature_names_out()

In [206]:
len(unigram_vocabulary)

203208

In [211]:
bigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2)
)

In [212]:
bigram_matrix = bigram_vectorizer.fit_transform(texts)

In [213]:
bigram_vocabulary = bigram_vectorizer.get_feature_names_out()

In [214]:
len(unigram_vocabulary)

203208

In [224]:
trigram_vectorizer = CountVectorizer(
    ngram_range=(2, 2)
)

In [225]:
trigram_matrix = trigram_vectorizer.fit_transform(texts)

In [226]:
trigram_vocabulary = trigram_vectorizer.get_feature_names_out()

In [227]:
print("Unigram vocabularysize:", len(unigram_vocabulary))

print("Bigram vocabulary size:", len(bigram_vocabulary))

print("Trigram vocabulary size:", len(trigram_vocabulary))

Unigram vocabularysize: 203208
Bigram vocabulary size: 2893018
Trigram vocabulary size: 2893018

# Part 4

In [200]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf_vectorizer = TfidfVectorizer()

In [ ]:
tfidf_matrix = tfidf_vectorizer.fit_transform(texts)

In [ ]:
tfidf_vectorizer.get_feature_names_out()

array(['absurd', 'account', 'accustomed', 'act', 'acting', 'action',
       'actor', 'actual', 'actually', 'adam', 'addiction', 'adrian',
       'adult', 'adventureoh', 'africa', 'afternoon', 'agenda', 'ago',
       'agreement', 'ahead', 'aid', 'air', 'alien', 'alivewe', 'allen',
       'alltime', 'almost', 'along', 'also', 'always', 'amateurish',
       'amazing', 'angle', 'annoy', 'another', 'anxiously', 'anymore',
       'anymoreits', 'anyone', 'apparently', 'appeal', 'appearance',
       'appreciate', 'area', 'argue', 'around', 'arquette', 'arthur',
       'artist', 'attachment', 'attack', 'attempt', 'audience', 'average',
       'await', 'awaken', 'away', 'awayi', 'awful', 'back', 'bad',
       'badass', 'band', 'bart', 'base', 'basically', 'beautiful',
       'become', 'begin', 'believable', 'believe', 'berkshire', 'best',
       'bette', 'beyond', 'big', 'bird', 'bisexual', 'bit', 'bitch',
       'bite', 'biz', 'bizarre', 'black', 'blatantly', 'boat', 'boll',
       'boogeyman', 'bore', 'boring', 'bowdler', 'bowdlerization', 'boy',
       'bratwurst', 'bread', 'brevity', 'brilliance', 'brilliant',
       'bring', 'brother', 'brutality', 'btw', 'budget', 'bump',
       'buscemi', 'busy', 'buy', 'call', 'camp', 'cant', 'cap', 'capture',
       'care', 'career', 'carol', 'carver', 'case', 'cast', 'cause',
       'cell', 'certain', 'chance', 'change', 'character', 'charm',
       'cheap', 'cheesy', 'child', 'childrens', 'choose', 'christian',
       'cinema', 'city', 'class', 'classic', 'clooney', 'closet', 'club',
       'come', 'comeback', 'comedy', 'comfort', 'comfortable', 'comment',
       'complain', 'complaint', 'complete', 'composition', 'concern',
       'conclusion', 'condition', 'connect', 'constant', 'contact',
       'continued', 'continuous', 'control', 'could', 'couldnt',
       'country', 'countryman', 'couple', 'creator', 'credit',
       'cromedalbino', 'crook', 'crown', 'cry', 'currently', 'cut', 'dad',
       'dan', 'dance', 'dangle', 'dare', 'dark', 'darker', 'date',
       'daughter', 'davis', 'dawson', 'dealing', 'death', 'decade',
       'decide', 'decides', 'decline', 'decorate', 'dedication',
       'delight', 'delivers', 'demented', 'descent', 'despite', 'destroy',
       'developed', 'development', 'devil', 'dialog', 'dialogue', 'diary',
       'didnt', 'die', 'different', 'direction', 'director', 'disappears',
       'disappoint', 'disappointed', 'disappointment', 'discern',
       'discomforting', 'disgraceful', 'dishwaterdull', 'divorce', 'do',
       'dodgy', 'doesnt', 'dont', 'doubt', 'dozen', 'dr', 'drama',
       'drawn', 'dream', 'dressedup', 'drop', 'drug', 'dude', 'due',
       'dvd', 'dy', 'earlier', 'early', 'eat', 'edit', 'effect', 'effort',
       'either', 'elijah', 'em', 'emerald', 'emotional', 'encounter',
       'encounterthe', 'encourage', 'end', 'england', 'english', 'enjoy',
       'enjoyed', 'enough', 'enters', 'entertaining', 'entire', 'entry',
       'episode', 'erain', 'erotic', 'etc', 'even', 'eventually', 'ever',
       'every', 'everybody', 'everything', 'evil', 'exactly', 'example',
       'examplesthe', 'excellent', 'except', 'exception', 'excitement',
       'expect', 'experience', 'experimental', 'extreme', 'extremely',
       'eye', 'face', 'fact', 'facts', 'factual', 'fail', 'faint', 'fall',
       'family', 'famous', 'fan', 'fantastic', 'fantasy', 'far',
       'fashion', 'fault', 'favor', 'favorite', 'feel', 'felt', 'female',
       'fight', 'film', 'filmit', 'final', 'find', 'fine', 'finsished',
       'first', 'fit', 'fitness', 'flat', 'flavor', 'focus', 'follow',
       'forget', 'formula', 'forte', 'forward', 'four', 'fresh',
       'friction', 'friend', 'frodo', 'front', 'fulfillment', 'fully',
       'fun', 'funny', 'game', 'gangsta', 'geneticallymutatedsoldiers',
       'george', 'german', 'get', 'ghost', 'give', 'glass', 'globe', 'gm',
       'gms', 'go', 'golden', 'good', 'goodis', 'grandiose', 'grandma',
       'graphic', 'great', 'greeting', 'grenier', 'grizzly', 'grow',
       'guard', 'guesthosts', 'guided', 'gunsmoke', 'gut', 'habitatthe',
       'hack', 'haggery', 'hail', 'halliwell', 'halliwells',
       'handselected', 'happen', 'happy', 'hard', 'hardcore', 'harvey',
       'havent', 'he', 'hear', 'hearted', 'hell', 'helloand',
       'helplessly', 'hence', 'hero', 'heros', 'heterosexual', 'high',
       'hold', 'home', 'hook', 'horrible', 'horror', 'horroras', 'hot',
       'hour', 'however', 'huge', 'human', 'humorbut', 'humour', 'huntif',
       'huntwe', 'hurriedly', 'hypnotizes', 'id', 'idea', 'ignore', 'im',
       'image', 'imagine', 'imperioli', 'imply', 'impressed', 'improve',
       'include', 'infiltrate', 'inhabit', 'injustice', 'inmate',
       'inmates', 'innovative', 'insight', 'instead', 'interest',
       'interesti', 'interesting', 'intrigue', 'invite', 'involve',
       'inwards', 'irish', 'island', 'italian', 'itgreat', 'ive', 'jack',
       'jackson', 'jake', 'janet', 'jewel', 'johanson', 'joke', 'jump',
       'juvenile', 'kane', 'keep', 'keitel', 'kick', 'kid', 'kier',
       'kill', 'killer', 'kind', 'king', 'know', 'knowledge', 'knowthe',
       'krieger', 'lab', 'lack', 'lame', 'last', 'later', 'latino',
       'laugh', 'laughter', 'learn', 'least', 'leave', 'legion', 'leigh',
       'less', 'lesson', 'let', 'level', 'liam', 'liberty', 'life',
       'lighthearted', 'likable', 'like', 'liked', 'line', 'little',
       'live', 'locate', 'loneley', 'loneliness', 'long', 'look',
       'looked', 'lose', 'losti', 'lot', 'lotr', 'love', 'loved',
       'lovethis', 'low', 'luck', 'lukas', 'luke', 'lumberjackwoods',
       'luxurious', 'machine', 'mad', 'main', 'mainly', 'mainstream',
       'major', 'make', 'man', 'manage', 'mangle', 'mannered', 'many',
       'manyaryans', 'mass', 'master', 'masterful', 'match', 'matrix',
       'matrixor', 'mattei', 'matteis', 'maximum', 'may', 'maybe',
       'meaning', 'meaningless', 'mediocrity', 'meet', 'mehehe', 'mei',
       'men', 'mention', 'mercs', 'mess', 'methe', 'michael', 'middle',
       'midget', 'midwest', 'might', 'mildly', 'mile', 'million',
       'minute', 'mistake', 'moellerthree', 'mom', 'money', 'monster',
       'moreso', 'mother', 'movie', 'moviesso', 'mr', 'much', 'mural',
       'muslims', 'must', 'na', 'naked', 'name', 'names', 'nasty', 'nazi',
       'nazis', 'near', 'need', 'neeson', 'nervous', 'never', 'new',
       'newbury', 'next', 'nice', 'nickel', 'nickname', 'noble',
       'nominate', 'nonsensewhat', 'notice', 'nowhere', 'obee',
       'obsessive', 'odd', 'oddness', 'offer', 'old', 'oldtimebbc', 'ole',
       'one', 'opera', 'order', 'original', 'orton', 'oswald', 'others',
       'outlet', 'owen', 'oz', 'pace', 'painfully', 'paint', 'painter',
       'palm', 'parachute', 'parent', 'partakingfor', 'particularly',
       'pas', 'pat', 'paul', 'penitentary', 'people', 'perfectioni',
       'perfectly', 'perform', 'performance', 'person', 'perspective',
       'petter', 'phil', 'picture', 'piece', 'place', 'planet', 'play',
       'player', 'please', 'plot', 'plus', 'point', 'polari', 'poop',
       'portrait', 'positive', 'possible', 'postal', 'power', 'prada',
       'preachy', 'predictable', 'present', 'pretty', 'prevents',
       'previous', 'prison', 'prisoner', 'privacy', 'probably', 'problem',
       'production', 'professor', 'progress', 'project', 'proof',
       'psycho', 'pull', 'punch', 'punchlinesat', 'quirky', 'quite',
       'quitif', 'ralf', 'rambo', 'rarely', 'rather', 'read', 'ready',
       'real', 'realism', 'realize', 'really', 'reason', 'recall',
       'recognition', 'recognize', 'recommand', 'reek', 'reference',
       'regard', 'relation', 'relationship', 'remain', 'remake',
       'remember', 'remind', 'renaissance', 'replace', 'research',
       'resolution', 'respect', 'respite', 'rest', 'resurrection',
       'return', 'rev', 'reviewer', 'rhyme', 'rich', 'ridiculous',
       'right', 'risk', 'role', 'roll', 'romanceoz', 'romantic', 'roof',
       'rosanna', 'rosario', 'ruin', 'rule', 'run', 'rush', 'sacrifice',
       'saturday', 'save', 'saw', 'say', 'saywould', 'scarlet', 'scary',
       'scene', 'scheisse', 'scheme', 'schmuck', 'schnitzlers', 'school',
       'schweiger', 'scientist', 'score', 'scottish', 'screen',
       'screenwriter', 'script', 'scuffle', 'sea', 'seahunt', 'seamless',
       'secret', 'section', 'security', 'see', 'seem', 'selflessness',
       'selfs', 'sell', 'sens', 'sense', 'serial', 'series', 'set', 'sex',
       'sexy', 'shady', 'shakespeare', 'shakespeareshakespeare', 'shame',
       'sheen', 'shenanigan', 'shirley', 'shoot', 'shot', 'show', 'side',
       'sidekick', 'similar', 'simpleton', 'simplistic', 'simply',
       'since', 'sincere', 'sister', 'sit', 'situation', 'skill', 'skin',
       'slow', 'snazzier', 'snow', 'soap', 'solid', 'someone',
       'something', 'sometimes', 'song', 'sophisticate', 'sorrow', 'sort',
       'souls', 'soundtrack', 'special', 'spend', 'spider', 'spirit',
       'spoiler', 'spot', 'squad', 'stage', 'star', 'stare', 'start',
       'startle', 'starve', 'state', 'stay', 'steal', 'stereotype',
       'steve', 'still', 'stilted', 'sting', 'stinker', 'stock', 'stoner',
       'story', 'storyline', 'stray', 'street', 'strike', 'struck',
       'stunning', 'style', 'stylishly', 'submitor', 'success',
       'suckthere', 'suddenly', 'summary', 'summer', 'superman',
       'suppose', 'sure', 'surface', 'surreal', 'suspect', 'sword',
       'sympathetic', 'take', 'tale', 'talented', 'taste', 'tear', 'tech',
       'technique', 'tell', 'ten', 'terminatorthere', 'terribly',
       'terrificly', 'terror', 'text', 'thank', 'thats', 'theater',
       'theme', 'there', 'theres', 'theyd', 'theyve', 'thing', 'think',
       'three', 'thrill', 'thriller', 'thumb', 'tiger', 'til', 'tils',
       'time', 'timethis', 'timid', 'tire', 'title', 'today', 'todayits',
       'together', 'tone', 'top', 'topsecret', 'totally', 'touch', 'town',
       'trade', 'traditional', 'transfer', 'tree', 'tropical', 'true',
       'truly', 'trust', 'try', 'tune', 'turn', 'tv', 'type', 'udo',
       'unassuming', 'unbelievable', 'uncomfortable', 'unflinching',
       'unintentional', 'upuh', 'use', 'usually', 'vader', 'vancouver',
       'variation', 'version', 'victim', 'victorian', 'videotape', 'view',
       'viewingthats', 'viewpoint', 'violence', 'visually', 'vivid',
       'voice', 'vote', 'waitit', 'wan', 'want', 'war', 'warn', 'wasnt',
       'waste', 'watch', 'watchable', 'water', 'way', 'wear', 'weekend',
       'weekyou', 'well', 'wellworn', 'werent', 'whats', 'white', 'whole',
       'wholl', 'wiff', 'williams', 'wilson', 'wish', 'witty', 'woman',
       'womanthis', 'wonderful', 'wood', 'woody', 'woodys', 'word',
       'wordit', 'work', 'world', 'worth', 'would', 'wouldnt', 'wrap',
       'wrench', 'write', 'year', 'yes', 'yoda', 'york', 'youll', 'young',
       'youre', 'zombie', 'zombieok'], dtype=object)

Matrix

In [ ]:
print(tfidf_matrix.toarray())

[[0.         0.         0.06848012 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.12838533 0.         ... 0.         0.         0.        ]]

Dataframe

In [ ]:
tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out()
)

print("\nTF-IDF DataFrame:")
print(tfidf_df)

TF-IDF DataFrame:
      absurd   account  accustomed       act    acting    action     actor  \
0   0.000000  0.000000     0.06848  0.000000  0.000000  0.000000  0.000000
1   0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.086632
2   0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
3   0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
4   0.000000  0.000000     0.00000  0.076020  0.000000  0.086483  0.000000
5   0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
6   0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
7   0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
8   0.000000  0.000000     0.00000  0.119697  0.000000  0.000000  0.000000
9   0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
10  0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
11  0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
12  0.000000  0.000000     0.00000  0.000000  0.054442  0.000000  0.000000
13  0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
14  0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.173012
15  0.131101  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
16  0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
17  0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.000000
18  0.000000  0.000000     0.00000  0.000000  0.000000  0.000000  0.097284
19  0.000000  0.128385     0.00000  0.000000  0.000000  0.000000  0.000000

     actual  actually      adam  ...     write      year       yes      yoda  \
0   0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
1   0.00000  0.000000  0.000000  ...  0.086632  0.000000  0.000000  0.000000
2   0.00000  0.000000  0.000000  ...  0.000000  0.081788  0.000000  0.000000
3   0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
4   0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
5   0.00000  0.000000  0.000000  ...  0.000000  0.110112  0.000000  0.000000
6   0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
7   0.00000  0.000000  0.000000  ...  0.082195  0.075295  0.000000  0.000000
8   0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
9   0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
10  0.14977  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
11  0.00000  0.000000  0.000000  ...  0.000000  0.168196  0.000000  0.000000
12  0.00000  0.054442  0.000000  ...  0.000000  0.000000  0.054442  0.000000
13  0.00000  0.000000  0.000000  ...  0.232612  0.000000  0.000000  0.000000
14  0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
15  0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
16  0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
17  0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.089638
18  0.00000  0.000000  0.122652  ...  0.000000  0.000000  0.000000  0.000000
19  0.00000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000

        york    youll     young     youre    zombie  zombieok
0   0.000000  0.06848  0.000000  0.000000  0.000000  0.000000
1   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
2   0.000000  0.00000  0.089283  0.000000  0.000000  0.000000
3   0.000000  0.00000  0.000000  0.110434  0.110434  0.110434
4   0.086483  0.00000  0.000000  0.000000  0.000000  0.000000
5   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
6   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
7   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
8   0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
9   0.000000  0.00000  0.218384  0.000000  0.000000  0.000000
10  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
11  0.000000  0.00000  0.091805  0.000000  0.000000  0.000000
12  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
13  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
14  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
15  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
16  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
17  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
18  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000
19  0.000000  0.00000  0.000000  0.000000  0.000000  0.000000

[20 rows x 968 columns]