# Assignment 17: Text Cleaning, Preprocessing and NLP Pipeline

In [150]:
import pandas as pd
import numpy as np

Dataset Name: TMDB 5000 Movie Dataset

Kaggle Link: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

## Part 1 : NLP Pipeline & Basic Text Cleaning

### Task 1: Understanding Raw Text Data

In [151]:
df = pd.read_csv('./IMDB Dataset.csv')

In [152]:
data = df.copy()

In [153]:
data.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [154]:
data.shape

(50000, 2)

In [155]:
data.sample(5)

                                                  review sentiment
35197  First off, I knew nothing about 'Mazes and Mon...  negative
15000  This movie really shows its age. The print I s...  negative
3532   I rented the dubbed-English version of Lensman...  negative
30502  A serious comedy. Ross Hunter-produced movie v...  positive
14655  I saw this last week after picking up the DVD ...  negative

In [156]:
data['review'].head()

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. <br /><br />The...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: review, dtype: str

Text Length

In [157]:
data['text_length'] = data['review'].str.len()

In [158]:
data[['review', 'text_length']].head()

                                              review  text_length
0  One of the other reviewers has mentioned that ...         1761
1  A wonderful little production. <br /><br />The...          998
2  I thought this was a wonderful way to spend ti...          926
3  Basically there's a family where a little boy ...          748
4  Petter Mattei's "Love in the Time of Money" is...         1317

In [159]:
data['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

Uppercase

In [160]:
any(char.isupper() for char in data['review'][0])

True

In [161]:
import re

In [162]:
numbers = re.findall(r'\d+', data['review'][0])
numbers

['1']

Extra Space

In [163]:
"  " in data['review'][0]

False

In [164]:
"  " in data['review'][1]

False

Html Tage

In [165]:
html = re.findall(r"<.*?>", data['review'][0])
html

['<br />', '<br />', '<br />', '<br />', '<br />', '<br />']

Punctuation

In [166]:
punctuation = re.findall(r"[^\w\s]", data['review'][1])
punctuation[:30]

['.',
 '<',
 '/',
 '>',
 '<',
 '/',
 '>',
 '-',
 '-',
 '-',
 ',',
 ',',
 '.',
 '<',
 '/',
 '>',
 '<',
 '/',
 '>',
 '-',
 '"',
 '"',
 '!',
 "'",
 ',',
 '.',
 "'",
 '.',
 '<',
 '/']

### Task 2: Basic Text Cleaning

In [167]:
def apply_lower_case(text):
    return text.lower()

In [168]:
data['review'] = data['review'].apply(apply_lower_case)

In [169]:
def punctuation_removal(text):
    return re.sub(r'[^\w\s]', '', text)

In [170]:
data['review'] = data['review'].apply(punctuation_removal)

In [171]:
punctuation = re.findall(r"[^\w\s]", data['review'][1])
punctuation[:30]

[]

In [172]:
def remove_html_tage(text):
    return re.sub(r"<.*?>", '', text)

In [173]:
data['review'] = data['review'].apply(remove_html_tage)

In [174]:
html = re.findall(r"<.*?>", data['review'][0])
html

[]

In [175]:
def remove_numbers(text):
    return re.sub(r"\d+", "", text)

In [176]:
data['review'] = data['review'].apply(remove_numbers)

In [177]:
def remove_extra_space(text):
    return re.sub(r"\s+", " ", text).strip()

In [178]:
data['review'] = data['review'].apply(remove_extra_space)

In [179]:
comparison = pd.DataFrame({'df1_review': df['review'], 'df2_review': data['review']})

In [180]:
comparison = comparison[comparison['df1_review'] != comparison['df2_review']]

In [184]:
comparison

,df1_review,df2_review
0,One of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,a wonderful little production br br the filmin...
2,I thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,basically theres a family where a little boy j...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter matteis love in the time of money is a ...
...,...,...
49995,I thought this movie did a down right good job...,i thought this movie did a down right good job...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,i am a catholic taught in parochial elementary...
49998,I'm going to have to disagree with the previou...,im going to have to disagree with the previous...
49999,No one expects the Star Trek movies to be high...,no one expects the star trek movies to be high...

## Part 2: Advanced Text Cleaning

### Task 3: Removing Noise

In [181]:
def url_removal(text):
    return re.sub(r"https?://\S+|www\.\S+", '', text)

In [182]:
data['review'] = data['review'].apply(url_removal)

In [185]:
def email_removal(text):
    return re.sub(r"https?://\S+|www\.\S+", '', text)

In [186]:
data['review'] = data['review'].apply(email_removal)

In [189]:
def find_email(text):
    return re.findall(r"https?://\S+|www\.\S+", text)

In [190]:
data['review'].apply(find_email)

0        []
1        []
2        []
3        []
4        []
         ..
49995    []
49996    []
49997    []
49998    []
49999    []
Name: review, Length: 50000, dtype: object